development: &default
  adapter: mysql
  database: twiddr_development
  username: root
  password:
  host: localhost
  encoding: utf8

test: &test
  <<: *default
  database: twiddr_test


cucumber:
  <<: *test